version: '3.7'

services:
  mongoDBCont:
    image: mongo:latest 
    container_name: mongoDBCont 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017 
    volumes:
      - mongodb_data_cont:/data/db
      #- ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
volumes:
    mongodb_data_cont:

